#macro WEST_WALL_TILE_TOP 38
#macro WEST_WALL_TILE_BOTTOM 36
#macro EAST_WALL_TILE_TOP 40
#macro EAST_WALL_TILE_BOTTOM 34
#macro NORTH_WALL_TILE_LEFT WEST_WALL_TILE_TOP
#macro NORTH_WALL_TILE_RIGHT EAST_WALL_TILE_TOP
#macro SOUTH_WALL_TILE_LEFT WEST_WALL_TILE_BOTTOM
#macro SOUTH_WALL_TILE_RIGHT EAST_WALL_TILE_BOTTOM
#macro SHADOW_TOP 68
#macro SHADOW_BOTTOM 76
#macro SHADOW_LEFT 64
#macro SHADOW_RIGHT 72
#macro TILE_CLEAR 0
#macro SHADOW_CLEAR 48
#macro DOOR_LEFT 1
#macro DOOR_RIGHT 2
#macro DOOR_SPRITE_NUM 4
#macro WEST_DOOR_OFFSET (1 * DOOR_SPRITE_NUM)
#macro EAST_DOOR_OFFSET (2 * DOOR_SPRITE_NUM)
#macro SOUTH_DOOR_OFFSET (3 * DOOR_SPRITE_NUM)
#macro OPEN_DOOR_OFFSET 2


// Logging macros
#macro CARD_CHOSEN "1"
#macro AUGMENT_CHOSEN "2"

#macro WING_CLEARED "10"
#macro BOSS_ENTRY "11"

#macro ENEMY_KILLED "20"
#macro ATTACK_SPELL_USED "21"
#macro SPECIAL_SPELL_USED "22"

#macro PLAYER_DEATH "30"
#macro START_GAME "31"

#macro PAUSED "50"

